openapi: 3.0.2

info:
  version: 0.0.1
  title: Projeto FI

servers:
  - url: http://localhost:5000
    description: Local

paths:

  /version:
    get:
      operationId: pontos.api.api_version
      summary: Retorna a versão da API
      responses:
        200:
          description: Success

  /cartao:
    get:
      operationId: pontos.api.cartoes.listar_cartoes
      description: Lista todos cartoes de clientes
      tags:
        - Cartoes
      # security:
      #   - oauth2: []
      parameters:
        - name: empresa_id
          in: query
          description: Id da empresa_id
          schema:
            type: integer
            nullable: true
        - name: programa_id
          in: query
          description: Id do programa de pontos
          schema:
            type: integer
        - name: page
          in: query
          description: Índice da página
          schema:
            type: integer
            nullable: true
        - name: page_size
          in: query
          description: Tamanho da página
          schema:
            type: integer
            nullable: true

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/Cartao"
        401:
          description: Not Authorized
        403:
          description: Not Allowed

  /cartao/{cartao_id}/ponto/adiciona:
    post:
      operationId: pontos.api.cartoes.adicionar_ponto
      description: Adiciona 1 ponto ao cartao
      tags:
        - Cartoes
      # security:
      #   - oauth2: [gerente]
      parameters:
        - name: cartao_id
          in: path
          description: ID do cartão
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cartao"                         
        400:
          description: Cartao não pode receber pontos
        401:
          description: Not Authorized
        403:
          description: Not Allowed
        404:
          description: Cartao não encontrado

  /cartao/{cartao_id}/ponto/remove:
    post:
      operationId: pontos.api.cartoes.remover_ponto
      description: Remove 1 ponto do cartao
      tags:
        - Cartoes
      # security:
      #   - oauth2: [gerente]
      parameters:
        - name: cartao_id
          in: path
          description: ID do cartao
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cartao"                         
        400:
          description: Cartao já resgatado ou não tem ponto para ser removido
        401:
          description: Not Authorized
        403:
          description: Not Allowed
        404:
          description: Cartao não encontrado

  /cartao/{cartao_id}/ponto/utiliza:
    post:
      operationId: pontos.api.cartoes.utilizar_pontos
      description: Utiliza cartao premiado e gera novo cartão em branco
      tags:
        - Cartoes
      # security:
      #   - oauth2: [gerente]
      parameters:
        - name: cartao_id
          in: path
          description: ID do cartao
          required: true
          schema:
            type: integer
            example: 1
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cartao"
        400:
          description: Cartao não pode ser utilizado
        401:
          description: Not Authorized
        403:
          description: Not Allowed
        404:
          description: Cartao não encontrado

  /auth/signin:
    post:
      operationId: pontos.api.auth.signin
      description: Faz login para obter JWT token
      tags:
        - Autenticação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: usuario@example.com
                password:
                  type: string
                  example: secrets

      responses:
        200:
          description: Token de acesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  usuario:
                    $ref: "#/components/schemas/Usuario"
                  token:
                    type: string
                    example: Encripted.JWT.Token
        400:
          description: Email ou senha inválida

components:

  securitySchemes:
    oauth2:
      type: oauth2
      x-tokenInfoFunc: pontos.services.token_services.check_token_info

  schemas:

    Cartao:
      type: object
      properties:
        id:
          type: integer
          example: 100
        empresa:
          $ref: "#/components/schemas/Empresa"
        programa_id:
          type: integer
          example: 1
        usuario:
          $ref: "#/components/schemas/Usuario"
        pontos:
          type: integer
          example: 3
        criado_em:
          type: string
          format: date-time
          example: 2021-01-11T11:32:28Z
        premiado_em:
          type: string
          format: date-time
          example: 2021-01-11T11:32:28Z
          nullable: true

    Usuario:
      type: object
      properties:
        id:
          type: integer
          example: 100
        nome_completo:
          type: string
          example: José da Silva
        fone:
          type: string
          example: 12991900999
        email:
          type: string
          example: jose@example.com
        avatar:
          type: string
          example: http://example.com/img/avatar/jose_thumb.png
          nullable: true
        perfil:
          type: string
          example: gerente ou cliente
        empresa_id:
          type: integer
          example: 1
          nullable: true
        criado_em:
          type: string
          format: date-time
          example: 2021-01-11T11:32:28Z

    Empresa:
      type: object
      properties:
        id:
          type: integer
          example: 100
        nome_completo:
          type: string
          example: Empresa Um
