name: Test github actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: pontos_test
          POSTGRES_PASSWORD: pontos123
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt

    - name: Create the database
      run: flask db upgrade
      env:
        FLASK_ENV: development
        FLASK_APP: pontos.app
        DATABASE_URI: postgresql://postgres:pontos123@localhost/pontos_test

    - name: Test with pytest
      run: pytest
      env:
        FLASK_ENV: development
        FLASK_APP: pontos.app
        DATABASE_URI: postgresql://postgres:pontos123@localhost/pontos_test
